USE [s17guest09]
GO

INSERT INTO [dbo].[Class]
           ([Title]
           ,[ClassDescription]
           ,[Duration]
           ,[DificultyLevelID])
     VALUES
           ('A dive into Data Quality Services',null,60,2),
('A Dynamic World Demands Dynamic SQL',null,60,2),
('A Dynamic World Demands Dynamic SQL',null,60,2),
('Absolute Introductory Session on SQL Server 2014 In-Memory Optimized Databases (Hekaton)',null,60,1),
('AlwaysOn: Improve reliability and reporting performance with one cool tech',null,60,1),
('An introduction to Data Mining',null,60,2),
('An Introduction to Database Design',null,60,1),
('Autogenerating a process data warehouse',null,60,3),
('Automate your daily checklist with PBM and CMS',null,60,2),
('Automated Installing and Configuration of SQL2014/SQL2012 AlwaysOn Across Multiple Datacenters',null,60,2),
('Automated Installing and Configuration of SQL2014/SQL2012 AlwaysOn Across Multiple Datacenters',null,60,2),
('Automating Execution Plan Analysis',null,60,3),
('Automating Execution Plan Analysis',null,60,3),
('Automating SQL Server using PowerShell',null,60,2),
('Balanced Scorecards using SSRS',null,60,2),
('Baselines and Performance Monitoring with PAL',null,60,1),
('Basic Database Design',null,60,1),
('Basic Database Programming',null,60,1),
('Become a BI Independent Consultant!',null,60,1),
('Becoming a Top DBA--Learning Automation in SQL Server',null,60,1),
('Best Practices Document',null,60,2),
('Best Practices for Efficient SSRS Report Creation',null,60,1),
('Biggest Loser: Database Edition',null,60,2),
('Building a BI Solution in the Cloud',null,60,2),
('Building an Effective Data Warehouse Architecture',null,60,1),
('Building an Effective Data Warehouse Architecture with the cloud and MPP',null,60,1),
('Bulk load and minimal logged inserts',null,60,3),
('Business Analytics with SQL Server & Power Map:Everything you want to know but were afraid to ask',null,60,2),
('Challenges to designing financial warehouses, lessons learnt',null,60,2),
('Change Data Capture in SQL Server 2008/2012',null,60,2),
('Changing Your Habits to Improve the Performance of Your T-SQL',null,60,1),
('Clusters Your Way: #SANLess Clusters for Physical, Virtual, and Cloud Environments',null,60,1),
('Clusters Your Way: #SANLess Clusters for Physical, Virtual, and Cloud Environments',null,60,4),
('Coffee Break',null,60,4),
('Creating A Performance Health Repository - using MDW',null,60,1),
('Creating efficient and effective SSRS BI Solutions',null,60,2),
('Creating efficient and effective SSRS BI Solutions',null,60,2),
('Data Partitioning',null,60,2),
('Data Tier Application Testing with NUnit and Distributed Replay',null,60,2),
('Database design for mere developers',null,60,2),
('Database design for mere developers',null,60,2),
('Database Design: Solving Problems Before they Start!',null,60,1),
('Database Modeling and Design',null,60,2),
('Database Virtualization and Drinking out of the Fire Hose',null,60,2),
('DAX and the tabular model',null,60,2),
('DBA FOR DUMMIES',null,60,1),
('Dealing With Difficult People',null,60,1),
('Development Lifecycle with SQL Server Data Tools and DACFx',null,60,2),
('Did You Vote Today? A DBAs Guide to Cluster Quorum',null,60,3),
('Dimensional Modeling Design Patterns: Beyond Basics',null,60,2),
('Dimensional Modeling Design Patterns: Beyond Basics',null,60,2),
('Diving Into Query Execution Plans',null,60,2),
('Dynamic SQL: Writing Efficient Queries on the Fly',null,60,1),
('Easy Architecture Design for HA and DR',null,60,2),
('Enhancing your career: Building your personal brand',null,60,1),
('Establishing a SLA',null,60,2),
('ETL not ELT! Common mistakes and misconceptions about SSIS',null,60,3),
('Event Kickoff and Networking',null,60,4),
('Execution Plans: What Can You Do With Them?',null,60,2),
('Faster, Better Decisions with Self Service Business Analytics',null,60,2),
('Full Text Indexing Basics',null,60,1),
('Get your Mining Model Predictions out to all',null,60,2),
('Getting a job with Microsoft',null,60,4),
('Graph Databases for SQL Server Professionals',null,60,2),
('Hacking Exposé - Using SSL to Protect SQL Connections',null,60,2),
('Hacking the SSIS 2012 Catalog',null,60,1),
('Hidden in plain sight: master your tools',null,60,2),
('Highly Available SQL Server in Windows Azure IaaS',null,60,2),
('How to Make a LOT More Money as a Consultant',null,60,1),
('How to Think Like the Engine',null,60,2),
('Hybrid Cloud Scenarios with SQL Server 2014',null,60,2),
('Hybrid Solutions: The Future of SQL Server Disaster Recovery',null,60,2),
('Implementing Data Warehouse Patterns with the Microsoft BI Tools',null,60,2),
('Inroduction to Triggers',null,60,1),
('Integrating Reporting Services with SharePoint',null,60,2),
('Integration Services (SSIS) for the DBA',null,60,2),
('Introducing Power BI',null,60,1),
('Introduction to Database Recovery',null,60,1),
('Introduction to High Availability with SQL Server',null,60,1),
('Introduction to Powershell for DBA''s',null,60,1),
('Introduction to SQL Server - Part 1',null,60,1),
('Introduction to SQL Server - Part 2',null,60,1),
('Is That A Failover Cluster On Your Laptop/Desktop?',null,60,2),
('Leaving the Windows Open',null,60,2),
('Lunch Break',null,60,4),
('Lunchtime Keynote',null,60,4),
('Master Data Services Best Practices',null,60,2),
('Master Data Services Disaster Recovery',null,60,2),
('Mind your language!! Cursors are a dirty word',null,60,2),
('Modern Data Warehousing',null,60,1),
('Monitoring Server health via Reporting Services dashboards',null,60,2),
('Monitoring SQL Server using Extended Events',null,60,1),
('Multidimensional vs Tabular - May the Best Model Win',null,60,2),
('Murder They Wrote',null,60,2),
('Never Have to Say "Mayday!!!" Again',null,60,1),
('Now you see it! Now you don’t! Conjuring many reports utilizing only one SSRS report.',null,60,2),
('Optimal Infrastructure Strategies for Cisco UCS, Nexus and SQL Server',null,60,4),
('Optimizing Protected Indexes',null,60,2),
('Partitioning as a design pattern',null,60,3),
('Power BI Components in Microsoft''s Self-Service BI Suite',null,60,1),
('Power to the people!!',null,60,2),
('PowerShell Basics for SQLServer',null,60,1),
('PowerShell for the Reluctant DBA / Developer',null,60,1),
('Prevent Recovery Amnesia – Forget the Backups',null,60,1),
('Query Optimization Crash Course',null,60,1),
('Raffle',null,60,4),
('Rapid Application Development with Master Data Services',null,60,2),
('Recovery and Backup for Beginners',null,60,1),
('Reduce, Reuse, Recycle: Automating Your BI Framework',null,60,2),
('Registrations',null,60,4),
('Replicaton Technologies',null,60,3),
('Reporting Services for Mere DBAs',null,60,2),
('Scaling with SQL Server Service Broker',null,60,3),
('Scaling with SQL Server Service Broker',null,60,3),
('Self-Service Data Integration with Power Query',null,60,1),
('Shortcuts to Building SSIS in .Net',null,60,1),
('So You Want To Be A Consultant?',null,60,1),
('SQL anti patterns',null,60,3),
('SQL Server 2012/2014 Columnstore index',null,60,2),
('SQL Server 2012/2014 Performance Tuning All Up',null,60,2),
('SQL Server 2014 Data Access Layers',null,60,2),
('SQL Server 2014 New Features',null,60,2),
('SQL Server AlwaysOn Availability Groups',null,60,1),
('SQL Server and the Cloud',null,60,1),
('SQL Server Compression and what it can do for you',null,60,3),
('SQL Server Reporting Services 2014 on Steroids!!',null,60,2),
('SQL Server Reporting Services Best Practices',null,60,2),
('SQL Server Reporting Services, attendees choose',null,60,2),
('SQL Server Storage Engine under the hood',null,60,2),
('SQL Server Storage internals: Looking under the hood.',null,60,3),
('SSIS 2014 Data Flow Tuning Tips and Tricks',null,60,1),
('Standalone to High-Availability Clusters over Lunch—with Time to Spare',null,60,2),
('Stress testing SQL Server',null,60,3),
('Table partitioning for Azure SQL Databases',null,60,1),
('Testing',null,60,1),
('The future of the data professional',null,60,1),
('The Quest for the Golden Record:MDM Best Practices',null,60,1),
('The Quest to Find Bad Data With Data Profiling',null,60,2),
('The Spy Who Loathed Me - An Intro to SQL Security',null,60,1),
('Tired of the CRUD? Automate it!',null,60,2),
('Top 5 Ways to Improve Your triggers',null,60,2),
('Tricks that have saved my bacon',null,60,1),
('T-SQL : Bad Habits & Best Practices',null,60,1),
('T-SQL for Application Developers - Attendees chose',null,60,2),
('Tune Queries By Fixing Bad Parameter Sniffing',null,60,2),
('Using Extended Events in SQL Server',null,60,3),
('Watch Brent Tune Queries',null,60,2),
('What every SQL Server DBA needs to know about Windows Server 10 Technical Preview',null,60,2),
('What exactly is big data and why should I care?',null,60,1),
('What is it like to work for Microsoft?',null,60,1),
('What’s new in SQL Server Integration Services 2012',null,60,2),
('Why do we shun using tools for DBA job?',null,60,2),
('Why OLAP? Building SSAS cubes and benefits of OLAP',null,60,2),
('You''re Doing It Wrong!!',null,60,2)



GO


